Converted EntryCommon to declarative mapping.
Moved ResourcesBearer out of the inheritance chain in that it does no longer
inherit from EntryCommon, to avoid this exception:

InvalidRequestError: Class <class '__main__.Executable'> has multiple mapped
bases: [<class '__main__.EntryCommon'>, <class '__main__.File'>]